function MonsterBar(){

  // let target = document.querySelector("#insert-here")
  // function addNewMonsterRow(){
  //   console.log("hit")
  //   let target = document.querySelector("#insert-here");
  //   let cln = target.previousSibling.cloneNode(true);
  //   target.appendChild(cln);
  //   target.prepend
  // }


  function addNewMonsterRow() {
    console.log("hit")
    let copiedNodeLocation = document.getElementById("copy-target");
    debugger;
    let clonedNode = copiedNodeLocation.cloneNode(true);
    document.getElementById("insert-here").prepend(clonedNode);
  }
  

    return (
      <div>
        <div id="copy-target">
          <select className="monster-bar">
              <option value="Aboleth">Aboleth</option>
              <option value="Acolyte">Acolyte</option>
              <option value="Adult Black Dragon">Adult Black Dragon</option>
              <option value="Adult Blue Dragon">Adult Blue Dragon</option>
              <option value="Adult Brass Dragon">Adult Brass Dragon</option>
              <option value="Adult Bronze Dragon">Adult Bronze Dragon</option>
              <option value="Adult Copper Dragon">Adult Copper Dragon</option>
              <option value="Adult Gold Dragon">Adult Gold Dragon</option>
              <option value="Adult Green Dragon">Adult Green Dragon</option>
              <option value="Adult Red Dragon">Adult Red Dragon</option>
              <option value="Adult Silver Dragon">Adult Silver Dragon</option>
              <option value="Adult White Dragon">Adult White Dragon</option>
              <option value="Air Elemental">Air Elemental</option>
              <option value="Allosaurus">Allosaurus</option>
              <option value="Ancient Black Dragon">Ancient Black Dragon</option>
              <option value="Ancient Blue Dragon">Ancient Blue Dragon</option>
              <option value="Ancient Brass Dragon">Ancient Brass Dragon</option>
              <option value="Ancient Bronze Dragon">Ancient Bronze Dragon</option>
              <option value="Ancient Copper Dragon">Ancient Copper Dragon</option>
              <option value="Ancient Gold Dragon">Ancient Gold Dragon</option>
              <option value="Ancient Green Dragon">Ancient Green Dragon</option>
              <option value="Ancient Red Dragon">Ancient Red Dragon</option>
              <option value="Ancient Silver Dragon">Ancient Silver Dragon</option>
              <option value="Ancient White Dragon">Ancient White Dragon</option>
              <option value="Androsphinx">Androsphinx</option>
              <option value="Animated Armor">Animated Armor</option>
              <option value="Ankheg">Ankheg</option>
              <option value="Ankylosaurus">Ankylosaurus</option>
              <option value="Ape">Ape</option>
              <option value="Archmage">Archmage</option>
              <option value="Assassin">Assassin</option>
              <option value="Awakened Shrub">Awakened Shrub</option>
              <option value="Awakened Tree">Awakened Tree</option>
              <option value="Axe Beak">Axe Beak</option>
              <option value="Azer">Azer</option>
              <option value="Baboon">Baboon</option>
              <option value="Badger">Badger</option>
              <option value="Balor">Balor</option>
              <option value="Bandit">Bandit</option>
              <option value="Bandit Captain">Bandit Captain</option>
              <option value="Banshee">Banshee</option>
              <option value="Barbed Devil">Barbed Devil</option>
              <option value="Basilisk">Basilisk</option>
              <option value="Bat">Bat</option>
              <option value="Bearded Devil">Bearded Devil</option>
              <option value="Behir">Behir</option>
              <option value="Berserker">Berserker</option>
              <option value="Black Bear">Black Bear</option>
              <option value="Black Dragon Wyrmling">Black Dragon Wyrmling</option>
              <option value="Black Pudding">Black Pudding</option>
              <option value="Blink Dog">Blink Dog</option>
              <option value="Blood Hawk">Blood Hawk</option>
              <option value="Blue Dragon Wyrmling">Blue Dragon Wyrmling</option>
              <option value="Boar">Boar</option>
              <option value="Bone Devil">Bone Devil</option>
              <option value="Brass Dragon Wyrmling">Brass Dragon Wyrmling</option>
              <option value="Bronze Dragon Wyrmling">Bronze Dragon Wyrmling</option>
              <option value="Brown Bear">Brown Bear</option>
              <option value="Bugbear">Bugbear</option>
              <option value="Bulette">Bulette</option>
              <option value="Camel">Camel</option>
              <option value="Cat">Cat</option>
              <option value="Centaur">Centaur</option>
              <option value="Chain Devil">Chain Devil</option>
              <option value="Chimera">Chimera</option>
              <option value="Chuul">Chuul</option>
              <option value="Clay Golem">Clay Golem</option>
              <option value="Cloaker">Cloaker</option>
              <option value="Cloud Giant">Cloud Giant</option>
              <option value="Cockatrice">Cockatrice</option>
              <option value="Commoner">Commoner</option>
              <option value="Constrictor Snake">Constrictor Snake</option>
              <option value="Copper Dragon Wyrmling">Copper Dragon Wyrmling</option>
              <option value="Couatl">Couatl</option>
              <option value="Crab">Crab</option>
              <option value="Crocodile">Crocodile</option>
              <option value="Cult Fanatic">Cult Fanatic</option>
              <option value="Cultist">Cultist</option>
              <option value="Cyclops">Cyclops</option>
              <option value="Darkmantle">Darkmantle</option>
              <option value="Death Dog">Death Dog</option>
              <option value="Deep Gnome (Svirfneblin)">Deep Gnome (Svirfneblin)</option>
              <option value="Deer">Deer</option>
              <option value="Deva">Deva</option>
              <option value="Dire Wolf">Dire Wolf</option>
              <option value="Djinni">Djinni</option>
              <option value="Doppelganger">Doppelganger</option>
              <option value="Draft Horse">Draft Horse</option>
              <option value="Dragon Turtle">Dragon Turtle</option>
              <option value="Dretch">Dretch</option>
              <option value="Drider">Drider</option>
              <option value="Drow">Drow</option>
              <option value="Druid">Druid</option>
              <option value="Dryad">Dryad</option>
              <option value="Duergar">Duergar</option>
              <option value="Dust Mephit">Dust Mephit</option>
              <option value="Eagle">Eagle</option>
              <option value="Earth Elemental">Earth Elemental</option>
              <option value="Efreeti">Efreeti</option>
              <option value="Elephant">Elephant</option>
              <option value="Elk">Elk</option>
              <option value="Erinyes">Erinyes</option>
              <option value="Ettercap">Ettercap</option>
              <option value="Ettin">Ettin</option>
              <option value="Fire Elemental">Fire Elemental</option>
              <option value="Fire Giant">Fire Giant</option>
              <option value="Flameskull">Flameskull</option>
              <option value="Flesh Golem">Flesh Golem</option>
              <option value="Flying Snake">Flying Snake</option>
              <option value="Flying Sword">Flying Sword</option>
              <option value="Frog">Frog</option>
              <option value="Frost Giant">Frost Giant</option>
              <option value="Gargoyle">Gargoyle</option>
              <option value="Gelatinous Cube">Gelatinous Cube</option>
              <option value="Ghast">Ghast</option>
              <option value="Ghost">Ghost</option>
              <option value="Ghoul">Ghoul</option>
              <option value="Giant Ape">Giant Ape</option>
              <option value="Giant Badger">Giant Badger</option>
              <option value="Giant Bat">Giant Bat</option>
              <option value="Giant Boar">Giant Boar</option>
              <option value="Giant Centipede">Giant Centipede</option>
              <option value="Giant Constrictor Snake">Giant Constrictor Snake</option>
              <option value="Giant Crab">Giant Crab</option>
              <option value="Giant Crocodile">Giant Crocodile</option>
              <option value="Giant Eagle">Giant Eagle</option>
              <option value="Giant Elk">Giant Elk</option>
              <option value="Giant Fire Beetle">Giant Fire Beetle</option>
              <option value="Giant Frog">Giant Frog</option>
              <option value="Giant Goat">Giant Goat</option>
              <option value="Giant Hyena">Giant Hyena</option>
              <option value="Giant Lizard">Giant Lizard</option>
              <option value="Giant Octopus">Giant Octopus</option>
              <option value="Giant Owl">Giant Owl</option>
              <option value="Giant Poisonous Snake">Giant Poisonous Snake</option>
              <option value="Giant Rat">Giant Rat</option>
              <option value="Giant Scorpion">Giant Scorpion</option>
              <option value="Giant Sea Horse">Giant Sea Horse</option>
              <option value="Giant Shark">Giant Shark</option>
              <option value="Giant Spider">Giant Spider</option>
              <option value="Giant Toad">Giant Toad</option>
              <option value="Giant Vulture">Giant Vulture</option>
              <option value="Giant Wasp">Giant Wasp</option>
              <option value="Giant Weasel">Giant Weasel</option>
              <option value="Giant Wolf Spider">Giant Wolf Spider</option>
              <option value="Gibbering Mouther">Gibbering Mouther</option>
              <option value="Glabrezu">Glabrezu</option>
              <option value="Gladiator">Gladiator</option>
              <option value="Gnoll">Gnoll</option>
              <option value="Goat">Goat</option>
              <option value="Goblin">Goblin</option>
              <option value="Gold Dragon Wyrmling">Gold Dragon Wyrmling</option>
              <option value="Gorgon">Gorgon</option>
              <option value="Gray Ooze">Gray Ooze</option>
              <option value="Green Dragon Wyrmling">Green Dragon Wyrmling</option>
              <option value="Green Hag">Green Hag</option>
              <option value="Grick">Grick</option>
              <option value="Griffon">Griffon</option>
              <option value="Grimlock">Grimlock</option>
              <option value="Guard">Guard</option>
              <option value="Guardian Naga">Guardian Naga</option>
              <option value="Gynosphinx">Gynosphinx</option>
              <option value="Half-Red Dragon Veteran">Half-Red Dragon Veteran</option>
              <option value="Harpy">Harpy</option>
              <option value="Hawk">Hawk</option>
              <option value="Hell Hound">Hell Hound</option>
              <option value="Hezrou">Hezrou</option>
              <option value="Hill Giant">Hill Giant</option>
              <option value="Hippogriff">Hippogriff</option>
              <option value="Hobgoblin">Hobgoblin</option>
              <option value="Homunculus">Homunculus</option>
              <option value="Horned Devil">Horned Devil</option>
              <option value="Hunter Shark">Hunter Shark</option>
              <option value="Hydra">Hydra</option>
              <option value="Hyena">Hyena</option>
              <option value="Ice Devil">Ice Devil</option>
              <option value="Ice Mephit">Ice Mephit</option>
              <option value="Imp">Imp</option>
              <option value="Invisible Stalker">Invisible Stalker</option>
              <option value="Iron Golem">Iron Golem</option>
              <option value="Jackal">Jackal</option>
              <option value="Killer Whale">Killer Whale</option>
              <option value="Knight">Knight</option>
              <option value="Kobold">Kobold</option>
              <option value="Kraken">Kraken</option>
              <option value="Lamia">Lamia</option>
              <option value="Lemure">Lemure</option>
              <option value="Lich">Lich</option>
              <option value="Lion">Lion</option>
              <option value="Lizard">Lizard</option>
              <option value="Lizardfolk">Lizardfolk</option>
              <option value="Mage">Mage</option>
              <option value="Magma Mephit">Magma Mephit</option>
              <option value="Magmin">Magmin</option>
              <option value="Mammoth">Mammoth</option>
              <option value="Manticore">Manticore</option>
              <option value="Marilith">Marilith</option>
              <option value="Mastiff">Mastiff</option>
              <option value="Medusa">Medusa</option>
              <option value="Merfolk">Merfolk</option>
              <option value="Merrow">Merrow</option>
              <option value="Mimic">Mimic</option>
              <option value="Minotaur">Minotaur</option>
              <option value="Minotaur Skeleton">Minotaur Skeleton</option>
              <option value="Mule">Mule</option>
              <option value="Mummy">Mummy</option>
              <option value="Mummy Lord">Mummy Lord</option>
              <option value="Nalfeshnee">Nalfeshnee</option>
              <option value="Night Hag">Night Hag</option>
              <option value="Nightmare">Nightmare</option>
              <option value="Noble">Noble</option>
              <option value="Nothic">Nothic</option>
              <option value="Ochre Jelly">Ochre Jelly</option>
              <option value="Octopus">Octopus</option>
              <option value="Ogre">Ogre</option>
              <option value="Ogre Zombie">Ogre Zombie</option>
              <option value="Oni">Oni</option>
              <option value="Orc">Orc</option>
              <option value="Otyugh">Otyugh</option>
              <option value="Owl">Owl</option>
              <option value="Owlbear">Owlbear</option>
              <option value="Panther">Panther</option>
              <option value="Pegasus">Pegasus</option>
              <option value="Phase Spider">Phase Spider</option>
              <option value="Pit Fiend">Pit Fiend</option>
              <option value="Planetar">Planetar</option>
              <option value="Plesiosaurus">Plesiosaurus</option>
              <option value="Poisonous Snake">Poisonous Snake</option>
              <option value="Polar Bear">Polar Bear</option>
              <option value="Pony">Pony</option>
              <option value="Priest">Priest</option>
              <option value="Pseudodragon">Pseudodragon</option>
              <option value="Pteranodon">Pteranodon</option>
              <option value="Purple Worm">Purple Worm</option>
              <option value="Quasit">Quasit</option>
              <option value="Quipper">Quipper</option>
              <option value="Rakshasa">Rakshasa</option>
              <option value="Rat">Rat</option>
              <option value="Raven">Raven</option>
              <option value="Red Dragon Wyrmling">Red Dragon Wyrmling</option>
              <option value="Reef Shark">Reef Shark</option>
              <option value="Remorhaz">Remorhaz</option>
              <option value="Rhinoceros">Rhinoceros</option>
              <option value="Riding Horse">Riding Horse</option>
              <option value="Roc">Roc</option>
              <option value="Roper">Roper</option>
              <option value="Rug of Smothering">Rug of Smothering</option>
              <option value="Rust Monster">Rust Monster</option>
              <option value="Saber-Toothed Tiger">Saber-Toothed Tiger</option>
              <option value="Sahuagin">Sahuagin</option>
              <option value="Salamander">Salamander</option>
              <option value="Satyr">Satyr</option>
              <option value="Scorpion">Scorpion</option>
              <option value="Scout">Scout</option>
              <option value="Sea Hag">Sea Hag</option>
              <option value="Sea Horse">Sea Horse</option>
              <option value="Shadow">Shadow</option>
              <option value="Shambling Mound">Shambling Mound</option>
              <option value="Shield Guardian">Shield Guardian</option>
              <option value="Shrieker">Shrieker</option>
              <option value="Silver Dragon Wyrmling">Silver Dragon Wyrmling</option>
              <option value="Skeleton">Skeleton</option>
              <option value="Solar">Solar</option>
              <option value="Spectator">Spectator</option>
              <option value="Specter">Specter</option>
              <option value="Spider">Spider</option>
              <option value="Spirit Naga">Spirit Naga</option>
              <option value="Sprite">Sprite</option>
              <option value="Spy">Spy</option>
              <option value="Steam Mephit">Steam Mephit</option>
              <option value="Stirge">Stirge</option>
              <option value="Stone Giant">Stone Giant</option>
              <option value="Stone Golem">Stone Golem</option>
              <option value="Storm Giant">Storm Giant</option>
              <option value="Succubus/Incubus">Succubus/Incubus</option>
              <option value="Swarm of Bats">Swarm of Bats</option>
              <option value="Swarm of Insects">Swarm of Insects</option>
              <option value="Swarm of Poisonous Snakes">Swarm of Poisonous Snakes</option>
              <option value="Swarm of Quippers">Swarm of Quippers</option>
              <option value="Swarm of Rats">Swarm of Rats</option>
              <option value="Swarm of Ravens">Swarm of Ravens</option>
              <option value="Tarrasque">Tarrasque</option>
              <option value="Thug">Thug</option>
              <option value="Tiger">Tiger</option>
              <option value="Treant">Treant</option>
              <option value="Tribal Warrior">Tribal Warrior</option>
              <option value="Triceratops">Triceratops</option>
              <option value="Troll">Troll</option>
              <option value="Twig Blight">Twig Blight</option>
              <option value="Tyrannosaurus Rex">Tyrannosaurus Rex</option>
              <option value="Unicorn">Unicorn</option>
              <option value="Vampire">Vampire</option>
              <option value="Vampire Spawn">Vampire Spawn</option>
              <option value="Veteran">Veteran</option>
              <option value="Violet Fungus">Violet Fungus</option>
              <option value="Vrock">Vrock</option>
              <option value="Vulture">Vulture</option>
              <option value="Warhorse">Warhorse</option>
              <option value="Warhorse Skeleton">Warhorse Skeleton</option>
              <option value="Water Elemental">Water Elemental</option>
              <option value="Weasel">Weasel</option>
              <option value="Werebear">Werebear</option>
              <option value="Wereboar">Wereboar</option>
              <option value="Wererat">Wererat</option>
              <option value="Weretiger">Weretiger</option>
              <option value="Werewolf">Werewolf</option>
              <option value="White Dragon Wyrmling">White Dragon Wyrmling</option>
              <option value="Wight">Wight</option>
              <option value="Will-o'-Wisp">Will-o'-Wisp</option>
              <option value="Winter Wolf">Winter Wolf</option>
              <option value="Wolf">Wolf</option>
              <option value="Worg">Worg</option>
              <option value="Wraith">Wraith</option>
              <option value="Wyvern">Wyvern</option>
              <option value="Xorn">Xorn</option>
              <option value="Yeti">Yeti</option>
              <option value="Young Black Dragon">Young Black Dragon</option>
              <option value="Young Blue Dragon">Young Blue Dragon</option>
              <option value="Young Brass Dragon">Young Brass Dragon</option>
              <option value="Young Bronze Dragon">Young Bronze Dragon</option>
              <option value="Young Copper Dragon">Young Copper Dragon</option>
              <option value="Young Gold Dragon">Young Gold Dragon</option>
              <option value="Young Green Dragon">Young Green Dragon</option>
              <option value="Young Red Dragon">Young Red Dragon</option>
              <option value="Young Silver Dragon">Young Silver Dragon</option>
              <option value="Young White Dragon">Young White Dragon</option>
              <option value="Zombie">Zombie</option>
          </select>
          <button onClick={addNewMonsterRow}>+</button>
        </div>
      <div id="insert-here"></div>
    </div>
  )
}

export default MonsterBar;